
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.hocuscodus.qed.lang;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVEQ = 44;
  public static final int PLUSPLUS = 19;
  public static final int STRING_LITERAL = 58;
  public static final int GTEQ = 33;
  public static final int MULT = 7;
  public static final int LTEQ = 32;
  public static final int MODEQ = 45;
  public static final int XOR = 38;
  public static final int LPAREN = 12;
  public static final int URSHIFT = 29;
  public static final int MINUS = 22;
  public static final int RPAREN = 13;
  public static final int BOOLEAN_LITERAL = 56;
  public static final int OROR = 41;
  public static final int CHARACTER_LITERAL = 57;
  public static final int AND = 37;
  public static final int NOT = 24;
  public static final int SEMICOLON = 6;
  public static final int LT = 30;
  public static final int OR = 39;
  public static final int COMMA = 8;
  public static final int COMP = 23;
  public static final int ANDAND = 40;
  public static final int DIV = 25;
  public static final int PLUSEQ = 46;
  public static final int MINUSEQ = 47;
  public static final int RSHIFTEQ = 49;
  public static final int PLUS = 21;
  public static final int NULL_LITERAL = 62;
  public static final int THIS = 60;
  public static final int DOT = 4;
  public static final int XOREQ = 52;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 20;
  public static final int SUPER = 61;
  public static final int error = 1;
  public static final int OREQ = 53;
  public static final int EQEQ = 34;
  public static final int NEW_LITERAL = 17;
  public static final int MULTEQ = 43;
  public static final int MOD = 26;
  public static final int EQ = 11;
  public static final int LBRACK = 2;
  public static final int URSHIFTEQ = 50;
  public static final int IMPORT = 16;
  public static final int ARROW = 5;
  public static final int COLON = 14;
  public static final int FLOATING_POINT_LITERAL = 55;
  public static final int LBRACE = 9;
  public static final int RBRACK = 3;
  public static final int PACKAGE = 15;
  public static final int RBRACE = 10;
  public static final int QUESTION = 42;
  public static final int LSHIFT = 27;
  public static final int AT = 36;
  public static final int WHILE_LITERAL = 18;
  public static final int GT = 31;
  public static final int LSHIFTEQ = 48;
  public static final int ANDEQ = 51;
  public static final int NOTEQ = 35;
  public static final int RSHIFT = 28;
  public static final int IDENTIFIER = 59;
  public static final int INTEGER_LITERAL = 54;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LBRACK",
  "RBRACK",
  "DOT",
  "ARROW",
  "SEMICOLON",
  "MULT",
  "COMMA",
  "LBRACE",
  "RBRACE",
  "EQ",
  "LPAREN",
  "RPAREN",
  "COLON",
  "PACKAGE",
  "IMPORT",
  "NEW_LITERAL",
  "WHILE_LITERAL",
  "PLUSPLUS",
  "MINUSMINUS",
  "PLUS",
  "MINUS",
  "COMP",
  "NOT",
  "DIV",
  "MOD",
  "LSHIFT",
  "RSHIFT",
  "URSHIFT",
  "LT",
  "GT",
  "LTEQ",
  "GTEQ",
  "EQEQ",
  "NOTEQ",
  "AT",
  "AND",
  "XOR",
  "OR",
  "ANDAND",
  "OROR",
  "QUESTION",
  "MULTEQ",
  "DIVEQ",
  "MODEQ",
  "PLUSEQ",
  "MINUSEQ",
  "LSHIFTEQ",
  "RSHIFTEQ",
  "URSHIFTEQ",
  "ANDEQ",
  "XOREQ",
  "OREQ",
  "INTEGER_LITERAL",
  "FLOATING_POINT_LITERAL",
  "BOOLEAN_LITERAL",
  "CHARACTER_LITERAL",
  "STRING_LITERAL",
  "IDENTIFIER",
  "THIS",
  "SUPER",
  "NULL_LITERAL"
  };
}

